# Generated by Django 5.1 on 2024-08-26 13:33

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Gastos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('categoria', models.CharField(choices=[('Lazer', 'Lazer'), ('Comida', 'Comida'), ('Tecnologia', 'Tecnologia'), ('viagem', 'viagem'), ('outros', 'outros')], max_length=100)),
                ('valor', models.CharField(max_length=100)),
                ('pagamento', models.CharField(choices=[('Dinheiro', 'Dinheiro'), ('Cartão de crédito', 'Cartão de crédito'), ('Cartão de débito', 'Cartão de débito'), ('Cheque', 'Cheque'), ('Pix', 'Pix'), ('Outros', 'Outros')], max_length=100)),
                ('banco', models.CharField(max_length=100)),
                ('dia', models.DateField(default=datetime.date.today)),
                ('dono', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dono', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
