# Generated by Django 5.1 on 2024-08-27 12:42

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_ganhos_gastos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ganhos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('categoria', models.CharField(choices=[('Trabalho', 'Trabalho'), ('Freelancer', 'Freelancer'), ('Presente', 'Presente'), ('Outros', 'Outros')], max_length=100)),
                ('valor', models.CharField(max_length=100)),
                ('banco', models.CharField(max_length=100)),
                ('dia', models.DateField(default=datetime.date.today)),
                ('dono', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dono2', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
