# Generated by Django 5.1 on 2024-08-27 15:24

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_ganhos_gastos', '0002_ganhos'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Extrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('valor', models.CharField(max_length=100)),
                ('dia', models.DateField(default=datetime.date.today)),
                ('ganho_gasto', models.BooleanField()),
                ('dono', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dono3', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
