# Generated by Django 5.1 on 2024-08-27 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_ganhos_gastos', '0003_extrato'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extrato',
            name='ganho_gasto',
            field=models.IntegerField(),
        ),
    ]
