# Generated by Django 5.1 on 2024-09-03 13:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_ganhos_gastos', '0004_alter_extrato_ganho_gasto'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GastosFixos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('categoria', models.CharField(choices=[('Lazer', 'Lazer'), ('Comida', 'Comida'), ('Tecnologia', 'Tecnologia'), ('viagem', 'viagem'), ('outros', 'outros')], max_length=100)),
                ('valor', models.CharField(max_length=100)),
                ('pagamento', models.CharField(choices=[('Dinheiro', 'Dinheiro'), ('Cartão de crédito', 'Cartão de crédito'), ('Cartão de débito', 'Cartão de débito'), ('Cheque', 'Cheque'), ('Pix', 'Pix'), ('Outros', 'Outros')], max_length=100)),
                ('banco', models.CharField(max_length=100)),
                ('dia_pagamento', models.CharField(max_length=100)),
                ('dono', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dono4', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
